### ISSUE TITLE
Matlab core function `floor` support

### ISSUE THREAD

**Issue by APgEDo** [mat2py/mat2py#39]
## 🚀 Feature Request
Matlab core function missing in mat2py, yet.

## 🔈 Motivation
Then we are using the Matlab function floor quite a lot, especially for getting values for counters. The trouble is, that the value looks like an integer, though in Python still is a float an due to that, one gets an error. Adding int(floor(…)) does the trick – maybe that would make sense to implement as floor always gives you some kind of integer and when combining it again with a float will give you a float – so it should not harm any operation. Though, this could be a problem, when using complex numbers or other data types (e.g. time). What do you think?

## 📝 Expected Results
```matlab
%% Basic functionality of floor
X = [-1.9  -0.2  3.4;  5.6  7.0  2.4+3.6i]

% Example 1 (from Matlab documentation)
Y = floor(X)
assert(Y == [-2.0000 + 0.0000i  -1.0000 + 0.0000i   3.0000 + 0.0000i; 5.0000 + 0.0000i   7.0000 + 0.0000i   2.0000 + 3.0000i])

% Example 2  (from Matlab documentation)
t = hours(8) + minutes(29:31) + seconds(1.23);
t.Format = 'hh:mm:ss.SS'
assert(t == [08:29:01.23   08:30:01.23   08:31:01.23])

Y1 = floor(t)
assert(t == [08:29:01.00   08:30:01.00   08:31:01.00])

Y2 = floor(t,'hours')
assert(t == [08:00:00.00   08:00:00.00   08:00:00.00])

% Example 3: check that there is no trouble using floor output in Python as index
y3 = X(1,floor(3.99))
assert(y1 == 3.4)

% Example 4: check that there is no trouble using floor output in Python as counter
for y4=1:floor(3.01)
end
assert(y4 == 3)
```

**Comment by chaoqing** [comment]
The `floor` function is designed to return float data type. If your concern is about when it used as matrix/loop index, then it has already been taken care of. See this [unit test](https://github.com/mat2py/mat2py/blob/7beee932e5a8e6bebaf0403238fb051c5f08eaa2/tests/test_elfun.py#L32) as example.

**Comment by APgEDo** [comment]
Dear @chaoqing, yes and no - you're right, my concern was regarding the matrix/loop indexing. Though, does floor work for you for time values - I did not get a test example to run properly (but maybe that is due to me using wrong time formats)? If it works for you I can close this issue.

**Comment by chaoqing** [comment]
For now, time type is not supported in any mat2py function. For now I did not consider time format support as my first priority.

**Comment by APgEDo** [comment]
All right - I just realized you commented that in the function code.

**Comment by APgEDo** [comment]
Dear @chaoqing getting further with my Matlab code I am getting an error for 
```python
Nz = floor(190/1) # Nz = 190.00
z = linspace(0, 0.02, Nz)
```
originating from the `floor` function not delivering an integer. This is no wrong behaviour of the `floor` function, but as it is related to the things we previously discussed - I placed it here. To my mind it is an issue in the converter `mh_python` but could aswell be related to `linspace` function.

Due to the same reason the following `for` loop fails (as the upper limit evaluates to a float of 6.000):
```python
for k in M[
    1 : (
        (
            floor( ( mrdivide( ( ( 0.0355 + 0.0345 ) / 2) - 0.03, 0.0405 - 0.03) ) @ M[100]) + 1)
            - floor(((mrdivide(0.0345 - 0.03, 0.0405 - 0.03)) @ M[100]) + 1)
        )
        + 1
    ) # this evaluates to {MatArray: (1,1)} [[6.]]
]:
    pass
```

**Comment by chaoqing** [comment]
Hi @APgEDo, I have fixed the linspace issue. 

I do not understand your second statement, the example should work except there is a syntax error. Could you try again or share the original Matlab code?

**Comment by APgEDo** [comment]
Hi @chaoqing, thanks for fixing the linspace issue – you are doing a fantastic job and I appreciate your efforts very, very much!!!

I separated the mathematical part of my Matlab function from the import/export part and then converted the relevant function with the [mat2py online converter](https://translate.mat2py.org/) to Python. Regarding my second statement, I am still (having the latest commits installed) facing issues with indices derived from floor calculations. The original Matlab code is:

```matlab
% R1 to R6, h, Nr and Nz being variables of type double
for k=1:floor(((R6+R5)/2-R2)/(R4-R2)*Nr+1)-floor((R5-R2)/(R4-R2)*Nr+1)+1     i=floor(Nz/2)+k-1; % z-coordinate increasing
    j=floor((R5-R2)/(R4-R2)*Nr+k); % r-coordinate increasing
    l=floor(Nz/2)-k+1; % z-coordinate decreasing
    o=floor(((R6+R5)/2-R2)/(R4-R2)*Nr+k); % r-coordinate further increasing
    p=floor((h-(R6-R5)/2)/(2*h)*Nz)+k-1; % z-coordinate increasing after decreasing
    if isempty(find(on, 1))==1
        q=floor((h+(R6-R5)/2)/(2*h)*Nz)-k+1; % z-coordinate decrasing after increasing
    else
        q=floor((h+(R6-R5)/2)/(2*h)*Nz)-k+2;
    end
    v(i,j)=r(floor((R5-R2)/(R4-R2)*Nr+k)); % no slip at ring surface at one edge
    v(l,j)=r(floor((R5-R2)/(R4-R2)*Nr+k)); % no slip at ring surface on other edge
    v(p,o)=r(floor(((R6+R5)/2-R2)/(R4-R2)*Nr+k)); % no slip at ring surface on other edge
    v(q,o)=r(floor(((R6+R5)/2-R2)/(R4-R2)*Nr+k));
        if i == l
            i=0;
        elseif p == q
            p=0;
        end
    row = [row; i;l;q;p];
    col = [col; j;j;o;o];
end
```

After conversion with mat2py online converter the code (line 100 ff.) looks like this:
```python
        for k in M[
            1 : (
                (
                    floor(((mrdivide(((R6 + R5) / 2) - R2, R4 - R2)) @ M[Nr]) + 1)
                    - floor(((mrdivide(R5 - R2, R4 - R2)) @ M[Nr]) + 1)
                )
                + 1
            )
        ]:
            i = (floor(Nz / 2) + k) - 1
            j = floor(((mrdivide(R5 - R2, R4 - R2)) @ M[Nr]) + k)
            l = (floor(Nz / 2) - k) + 1
            o = floor(((mrdivide(((R6 + R5) / 2) - R2, R4 - R2)) @ M[Nr]) + k)
            p = (floor((mrdivide(h - ((R6 - R5) / 2), 2 * h)) @ M[Nz]) + k) - 1
            if isempty(find(on, 1)) == 1:
                q = (floor((mrdivide(h + ((R6 - R5) / 2), 2 * h)) @ M[Nz]) - k) + 1
            else:
                q = (floor((mrdivide(h + ((R6 - R5) / 2), 2 * h)) @ M[Nz]) - k) + 2
            v[I[i, j]] = r(floor(((mrdivide(R5 - R2, R4 - R2)) @ M[Nr]) + k))
            v[I[l, j]] = r(floor(((mrdivide(R5 - R2, R4 - R2)) @ M[Nr]) + k))
            v[I[p, o]] = r(
                floor(((mrdivide(((R6 + R5) / 2) - R2, R4 - R2)) @ M[Nr]) + k)
            )
            v[I[q, o]] = r(
                floor(((mrdivide(((R6 + R5) / 2) - R2, R4 - R2)) @ M[Nr]) + k)
            )
            if i == l:
                i = 0
            elif p == q:
                p = 0
            row = M[
                row,
                i,
                l,
                q,
                p,
            ]
            col = M[
                col,
                j,
                j,
                o,
                o,
            ]

```
 
but ends up with the following debug messages:
```
  File "…\DWR_osc_corr.py", line 100, in AP_DWR_osc_corr
    for k in M[
  File "…\Python310\lib\site-packages\mat2py\core\_internal\array.py", line 424, in __class_getitem__
    return MatCreator(args)
  File "…\\Python310\lib\site-packages\mat2py\core\_internal\array.py", line 402, in __new__
    return colon(args).view(MatArray)
  File "…\\Python310\lib\site-packages\mat2py\core\_internal\array.py", line 595, in view
    start, stop, step = self._convert_to_slice()
  File "…\\Python310\lib\site-packages\mat2py\core\_internal\array.py", line 562, in _convert_to_slice
    else np.finfo(float).eps * 100.0
  File "…\\Python310\lib\site-packages\numpy\core\getlimits.py", line 462, in __new__
    dtype = numeric.dtype(type(dtype))
TypeError: 'NoneType' object is not callable
```

**Comment by chaoqing** [comment]
Sorry I still did not see a clear issue with mat2py implementation. Based on your stack trace the issue happened when calling `M` to create the array using colon syntax. Could you provide information on your Python and Numpy version? It may be because Numpy introduced compatibility issue from the stack trace info.

BTW, feel free to reopen the issue if needed.

**Comment by APgEDo** [comment]
python version is 3.10.2
numpy version is 1.22.3
May be to add: The reason for this trouble is that
`for x in [lowerlimit : upperlimit]: do it`
lowerlimit and upperlimit may not be float values, meaning upperlimit = 6.0 will cause an error
![image](https://user-images.githubusercontent.com/104640641/167782560-98cf147a-094d-4bdd-91a8-336de75237a1.png)

**Comment by chaoqing** [comment]
I do not understand. The case about `upperlimit` to be float have already been taken care of long time ago. And you can check this [unit case](https://github.com/mat2py/mat2py/blob/b828c46089960ee4066bedd826f49a55bbc0670a/tests/test_elfun.py#L33) which works. Maybe you can insert an command there like `upperlimit = floor(6.1)` and test again? Also, could you print the `upperlimit.dtype, upperlimit.shape, upperlimit.view(np.ndarray)` before line 115?

**Comment by chaoqing** [comment]
I installed the same version of Python/Numpy but can not reproduce your issue.
<img width="1020" alt="截屏2022-05-11 下午11 30 47" src="https://user-images.githubusercontent.com/2959260/167889598-14213db5-2824-4c16-94e6-d58e5b0da438.png">

**Comment by APgEDo** [comment]
Hi @chaoqing, the unit test passes successfully for me as well, though the behaviour in the bigger context remains the same.
I changed `upperlimit = floor(6.1)` as suggested, but the error output stays the same. Regarding your request on upperlimit the outputs are:
```
print(upperlimit.dtype)
>>>float64
print(upperlimit.shape)
>>>(1, 1)
print(upperlimit.view(np.ndarray))
>>>[[6.]]
```
Additionally I tested if a range with float items runs into trouble, but the following unit test passes successfully:
```
# loop with range items of type float
for y5 in M[1: 6.0]:
    print("M[1:6.0] >", y5)
assert(isequal(y5, 6.0))
```
I successfully executed this minimal example solely and having deleted all of the rest of the code despite `for k in M[1: 6.0]: print(k)` - both of it works when executing the code.
**But** when I run the code in debug mode it fails and throws these errors. **So the trouble only occurs running in debug mode and only when using floats!**
So, maybe the issue is triggered by the debugger of my IDE "PyCharm CE 2022.1"? Could you try this (`for y5 in M[1: 6.0]: print(y5)`) with your setup?

**Comment by chaoqing** [comment]
I am wondering why you can use the function `print` as it is not implemented yet. For now, `disp` serve the purpose of `print`. For me, `for y5 in M[1: 6.0]: disp(y5)` work in both debug and release mode(under `PyCharm 2022.1 (Professional Edition)`). But I indeed suspect that PyCharm debugger will change the Mat2Py internal state when I develop `M`, which is very hard to capture. I used lazy evaluation technique for `colon` to boosting TPUT but I observed the debugger will trigger the lazy evaluation earlier.

The discussion for this thread is long and seems not related to `floor` function. Could you help create a minimal reproducible script and fire another **bug report**?

**Comment by APgEDo** [comment]
Just to answer your open question:
> I am wondering why you can use the function `print` as it is not implemented yet.
I just commented it out to be able to use the Python basic version of `print` - sorry, if that confused you. I will use `disp `now as suggested.
