### ISSUE TITLE
Matlab core function `inpolygon` support

### ISSUE THREAD

**Issue by APgEDo** [mat2py/mat2py#40]
## 🚀 Feature Request
Matlab core function **inpolygon** missing in mat2py, yet.

## 🔈 Motivation
I need this function to evaluate if points are within, on or outside of a polygon area. Depending on the number of variables requested it returns only points inside the polygon or additionally points which are on the edge of the polygon.

## 📝 Expected Results
```matlab
close all; % close all plot windows - may be ignored if plotting function not used below
P = [pi*1/4   pi*3/4    pi*5/4    pi*7/4 pi*1/4];
L = [pi*1/4   pi*3/4    pi*5/4    pi*7/4 pi*1/4 nan 0	1.25663706143592	2.51327412287183	3.76991118430775	5.02654824574367	6.28318530717959];
xvp = cos(P)';
yvp = sin(P)';
xv = cos(L)';
yv = sin(L)';


xq = [0.5377	1.8339	-2.2588	0.8622	0.3188	-1.3077	-0.4336	0	1	2.7694];
yq = [-0.8637	0.0774	-1.2141	-1.1135	-0.0068	1.5326	-0.7697	sin(pi/4)	0	1.1174];
[inp,onp] = inpolygon(xq,yq,xvp,yvp);
assert(isequal(inp, [0   0   0   0   1   0   0   1   0   0]), "'inpolygon' fails for parameters inside pentagon")
assert(isequal(onp, [0   0   0   0   0   0   0   1   0   0]), "'inpolygon' fails for parameters on pentagon")
[in,on] = inpolygon(xq,yq,xv,yv);
assert(isequal(in, [0  0   0   0   1   0   0   1   1   0]), "'inpolygon' fails for parameters inside intersecting pentagon and rectangle")
assert(isequal(on, [0  0   0   0   0   0   0   1   1   0]), "'inpolygon' fails for parameters on intersecting pentagon and rectangle")


% The following code is just for visualization and may be ignored
% Though it would be beautiful to have plot functionality implemented
figure
plot(xv,yv,'k:')
axis equal
hold on
plot(xq(in),yq(in),'bo')
plot(xq(on),yq(on),'r.')
plot(xq(~in),yq(~in),'m+')
hold off
```
The output figure should look like this
![image](https://user-images.githubusercontent.com/104640641/166231774-ff356597-4115-4742-bcda-b70e7680d029.png)

## 📎 Additional context
Depending on the number of variables requested it returns only points inside the polygon or additionally points which are on the edge of the polygon.

**Comment by chaoqing** [comment]
Hi @APgEDo, I do not have enough time to dig into why your unit test do not work. Could you help do a step-by-step debugging to find out where the difference emerge between Matlab and mat2py version? You can place breakpoint inside [this](https://github.com/mat2py/mat2py/blob/88997e6edd97bd36a58fed433e27890487495768/tests/test_inpolygon.py#L249) function call.

**Comment by APgEDo** [comment]
Hi @chaoqing, I think the error occurs at [line 66](https://github.com/mat2py/mat2py/blob/88997e6edd97bd36a58fed433e27890487495768/tests/test_inpolygon.py#L66) due to different shapes of `inbounds: (2,1)` and `on: (1,2)`. 
```python
inbounds = [[5], [8]]
_not(on) = [[ True True]]
```
In your code `on` and `_in` both get values and shape (1,2) in `vec_inpolygon` function. As I do not fully understand the operations performed there - I can just guess that reshaping the input arguments `xv` and `yv` in this subfunction from `matarray (5,2)` to `matarray (10,1)` would do the job, but I am not sure. Below find my debugging screenshot - maybe that helps.
![image](https://user-images.githubusercontent.com/104640641/166935147-131f52b3-c769-4e23-9163-a5b5078646b0.png)

**Comment by chaoqing** [comment]
I believe I have fixed this function. You can run you provided unit test [here](https://github.com/mat2py/mat2py/blob/ee52dd3679719e81247cf24a5af0dcea6c017189/tests/test_inpolygon.py#L41).

**Comment by chaoqing** [comment]
I believe I have fixed this function. You can run you provided unit test [here](https://github.com/mat2py/mat2py/blob/ee52dd3679719e81247cf24a5af0dcea6c017189/tests/test_inpolygon.py#L41).

**Comment by chaoqing** [comment]
Just make a note here. I made some changes to the `Matlab 2015b` original source code(use `edit inpolygon` to open it). With `mh_python` or [online translator](https://translate.mat2py.org/), the translated [source code](https://github.com/mat2py/mat2py/blob/main/mat2py/toolbox/matlab/polyfun/inpolygon.py) can work directly without further polish.

This is what I mean "Mat2Py intend to be a **drop-in replacement** of Matlab". The patch on `inpolygon.m` is necessary because some Matlab features(like implicit nargout, automatic type case, expand/shrink array) are not implemented yet and may not be there in short term.

Use following command to create the patched version:

```shell
patch /path/to/matlab_root/toolbox/matlab/polyfun/inpolygon.m -o /dev/stdout <<EOF
78c78
<     in = false(inputSize);
---
>     in = zeros(inputSize)~=0;
114c114
<         in = vec_inpolygon(Nv,x,y,xv,yv);
---
>         [in, ~] = vec_inpolygon(Nv,x,y,xv,yv);
119c119
<     in = false(1,M);
---
>     in = zeros(1,M)~=0;
121c121
<         on = false(1,M);
---
>         on = zeros(1,M)~=0;
180c180
< quad = (negX & posY) + 2*(negX & negY) + ...
---
> quad = (negX & posY) + 2.0*(negX & negY) + ...
257,258c257,258
<     xv(redundantNaN) = [];
<     yv(redundantNaN) = [];
---
>     xv = xv(~redundantNaN);
>     yv = yv(~redundantNaN);
262,263c262,263
<         xv(end+1) = NaN;
<         yv(end+1) = NaN;
---
>         xv = [xv; NaN];
>         yv = [yv; NaN];
284,285c284,285
<     xv(end) = [];
<     yv(end) = [];
---
>     xv = xv(1:end-1);
>     yv = yv(1:end-1);
300a301,304
>             if idxOffset+endIdx+1>size(xvnew, 1)
>                 xvnew = [xvnew;zeros(idxOffset+endIdx+1-size(xvnew, 1), 1)]
>                 yvnew = [yvnew;zeros(idxOffset+endIdx+1-size(yvnew, 1), 1)]
>             end
EOF
```

**Comment by APgEDo** [comment]
Dear @chaoqing, the `inpolygon` function works for me now - this is great! Thanks for that. I realized now that implementing this function was quiet challenging.
