### ISSUE TITLE
Matlab core function `isempty` support

### ISSUE THREAD

**Issue by APgEDo** [mat2py/mat2py#41]
## 🚀 Feature Request
Matlab core function **isempty** missing in mat2py, yet.

## 🔈 Motivation
Needed to see if any dimension of an matharray is empty (has the length zero).

## 📝 Expected Results
```matlab
%% Test basic functionality 
A = [1  2   3; 4   5   6; 0 0  nan]
B = []
a0 = isempty(A)
b0 = isempty(B)
assert(a0 == 0)
assert(b0 == 1)
```
## 📎 Additional context
Assumption for implementation by using numpy.py:
```python
np.count_nonzero(a.shape) == 0
```

**Comment by chaoqing** [comment]
This have also been implemented in v0.0.14. Please close the issue if you verified it have been solved.

**Comment by APgEDo** [comment]
Yes, unit tested this and it works for me - thanks!

**Comment by APgEDo** [comment]
I encountered an error for `isempty(find(Myarray, 1))`. To troubleshoot I separated the functions and for this case it works, but not the inline version...
```python
Myarray = M[[False, False, False], [False, True, False], [False, False, False]]
isinside = find(Myarray , 1)
>>> [[5]]
coolbool1 = isempty(isinside)
>>> [[0]]
coolbool2 = isempty(find(Myarray, 1))
>>> error
```
The last case fails with syntax error in line 147 of helper.py

**Comment by chaoqing** [comment]
This is not related to `isempty` but `find` instead. For those Matlab functions which have `nargout` support, I used the stack information and source code to automatically detecting how many return values needed. This feature is not stable or smart enough for now. For example, the interactive python environment do not provide enough calling stack information for mat2py to inference the `nargout` value. Normally this should not happen if you call the function from a python script file. I have a solution to automatically detecting it within [https://console.mat2py.org/]() (not delivered yet) but it do not work for other out-of-box python interactive interpreter.

To solve the issue you have right now, you must use command like `coolbool2 = isempty(find(Myarray, 1, nargout=1))` to provide `nargout` explicitly.

**Comment by APgEDo** [comment]
This workaround does the trick. Thanks for this solution!
