### ISSUE TITLE
Matlab core function `find` support

### ISSUE THREAD

**Issue by APgEDo** [mat2py/mat2py#42]
## 🚀 Feature Request
Functionalities of Matlab's core function **find** missing in mat2py, yet.

## 🔈 Motivation
"find" function should find elements in a matarray. If two arguments are given the second defines the number of elements to return. There are implementations for one argument and for two arguments, but currently the two argument case seems not to be implemented, as I get a not implemented error.

## 📝 Expected Results
```matlab
%% Test basic functionality 
X = [0     0     3    13
     5    11    10     8
     9     7     0    12
     4    14    15     0]
k = find(X<10, 5) % return the first 5 elements of X with values below 10
assert(isequal(k, [1; 2; 3; 4; 5]))
n0 = find(~X) % return the elements of X with zero values
assert(isequal(n0, [1; 5; 11; 16]))
last3nz = find(X,3,'last') % return the last three elements with nonzero values
assert(isequal(last3nz, [13; 14; 15]))
firstnz = find(X, 1)
assert(firstnz == 2)
```
## 📎 Additional context
Assumption for implementation by using numpy.py:
```python
return np.argwhere(x.reshape(-1))[:]
```

**Comment by chaoqing** [comment]
Implemented in recent commits.

**Comment by APgEDo** [comment]
Working for me now - thanks!
