### ISSUE TITLE
Matlab core function `mean` support

### ISSUE THREAD

**Issue by APgEDo** [mat2py/mat2py#43]
## 🚀 Feature Request
Matlab core function **mean** missing in mat2py, yet.

## 🔈 Motivation
"all" argument of "mean" function is not implemented, yet. In Python this should be equal to an execution without arguments.

## 📝 Expected Results
```matlab
%% Test basic functionality 
A = [0 1 2; 2 3 4; 0 4 2; 4 2 6]

Mcol = mean(A)
assert(isequal(Mcol, [1.5, 2.5, 3.5]))
Mdim2 = mean(A,2)
assert(isequal(Mdim2, [1; 3; 2; 4]))
Mall = mean(A,'all')
assert(Mall == 2.5)
```
## 📎 Additional context

**Comment by chaoqing** [comment]
@APgEDo I am using Matlab 2015b which do not support this `all` in mat2py v0.0.13.
But I have already added support for it in v0.0.14. Please try again v0.0.14.
Please upgrade your mat2py with command `pip3 install -U mat2py`.

BTW, I may not bump the mat2py version too frequently into Pypi when implementing your requests. So please use `pip3 install -U git+https://github.com/mat2py/mat2py` to install a nightly build version.

**Comment by APgEDo** [comment]
Passes successfully my unit test, meaning `all` argument (R2018b and later) works.
```python
    def test_mean_function(self):
        A = M[[0, 1, 2], [2, 3, 4], [0, 4, 2], [4, 2, 6]]
        Mcol = mean(A)
        assert(np.array_equal(Mcol, M[[1.5, 2.5, 3.5]]), "standard check without additional arguments")
        Mdim2 = mean(A, 2)
        assert(np.array_equal(Mdim2, M[1, 3, 2, 4]), "check with dimension argument for 'row-wise' averaging")
        Mall = mean(A, 'all')
        assert(Mall == 2.5, "additional argument 'all'")
```
