### ISSUE TITLE
Matlab core function `any` support

### ISSUE THREAD

**Issue by APgEDo** [mat2py/mat2py#44]
## 🚀 Feature Request
Matlab core function **any** missing in mat2py, yet.

## 🔈 Motivation
"mean" function is implemented, but just passes without execution of code. 

## 📝 Expected Results
```matlab
%% Test basic functionality 
A = [0 1 2; 2 3 4; 0 4 2; 4 2 6]

Any = any(A)
assert(isequal(Any, [1, 1, 1]))

Any1 = any(A == 1)
assert(isequal(Any1, [0, 1, 0]))

AnyAll = any(A, 'all')
assert(isequal(AnyAll, 1))

AnyDim2 = any(A == 3, 2)
assert(isequal(AnyDim2, [0; 1; 0; 0]))
```
## 📎 Additional context
To my mind this function should be equal to the numpy version:
```python
return np.any(args)
```

**Comment by chaoqing** [comment]
It has already been implemented, but not imported because it is not in `__all__` of `mat2py.core`. I have plan to solve all of those importing issue but for now you can just import it yourself like [here](https://github.com/mat2py/mat2py/blob/7beee932e5a8e6bebaf0403238fb051c5f08eaa2/tests/test_ops.py#L69) did.

**Comment by APgEDo** [comment]
Temporary implementation by `from mat2py.core.ops import _any` works for me and passes my unit test:
```python
    def test_any_function(self):
        A = M[[0, 1, 2], [2, 3, 4], [0, 4, 2], [4, 2, 6]]
        An = _any(A)
        assert(np.array_equal(An, M[[1, 1, 1]]),"standard check without additional arguments")
        Any1 = _any(A == 1)
        assert(np.array_equal(Any1, M[[0, 1, 0]]), "check with comparison, but without additional arguments")
        AnyAll = _any(A, 'all')
        assert(np.array_equal(AnyAll, 1), "additional argument 'all'")
        AnyDim2 = _any(A == 3, 2)
        assert(np.array_equal(AnyDim2, M[0, 1, 0, 0,]), "advanced check with dimension argument")
```
