### ISSUE TITLE
Syntax conversion error

### ISSUE THREAD

**Issue by APgEDo** [mat2py/mat2py#46]
## Checklist

- [ x] I've searched the project's [`issues`](https://github.com/mat2py/mat2py/issues?q=is%3Aissue).

## ❓ Question

Using the current version of the online Matlab to Python converter the Matlab code:
```matlab
f = freq(b);
```
is converted as is to Python code:
```python
f = freq(b);
```
freq is an array of values and b is the indexing variable and not a function, meaning that the correct Python code should look like:
```python
f = freq[b];
```

Is it possible to achieve this conversion or is it for this special case impossible to securely distinguish if freq is a function or not?

**Comment by chaoqing** [comment]
You do not need to distinguish function or variable here. If variable freq have been defined in current context, then freq(q) should give you a sub-matrix. Or the function will be called.

**Comment by APgEDo** [comment]
I do not fully understand your comment and currently using `freq(b)` does not work for me, but it is more likely that I am running into this problem as I am deviating from my Matlab code for the input by reading input variables from an input CSV file using pandas.py (as this gives me the opportunity to easily read data by header names and write data). To get values from the file I use code not originating from Matlab. Therefore each of these variables is defined as a numpy array read from the corresponding column of `dat`.
```python
freq = np.asarray(list(dat['freq']))
```
When I afterwards use
```python
f = freq(b) 
```
I get a `TypeError: ‘numpy.ndarray’ object is not callable`
Therefore I thought the problem would be the round brackets syntax and when I changed it locally to square brackets my Python code compiled without errors. Could you give me a hint, how to cope with this?

**Comment by chaoqing** [comment]
This is the warning I talked about before, do not mix Matlab generated code with your hand written code. If you insist to do this, you should first cast the raw numpy array into Mat2py array. 

- first convert all your matlab logic with the mh_python utility, say following matlab.m into matlab.py
    ```matlab
    function [output, more_output] = wrap_original_matlab_code_as_function(freq)
    output = [1,2,3];
    more_output = output+max(freq, 'all');
    ```

Try your best to make sure the upper generated python code work out of the box. If you found Matlab core functions not implemented, send a request or adapt the Matlab source code. Like you can replace  `max(A, 'all')` with `max(max(A))` or `max(reshape(A, 1, []))`.

- then write another python file to import upper generated function
    ```python
    from mat2py.core import M
    from .matlab imort wrap_original_matlab_code_as_function
    ...
    freq = dat['freq'].to_numpy()
    a, b = wrap_original_matlab_code_as_function(M[freq]) # note this type conversion with `M`
    
    # you can also cast a,b back to numpy.array with following code
   a = a.view(np.ndarray)
   ```

**Comment by APgEDo** [comment]
Thank you so much - I will try this and come back to you, but I will close this issue now - as it is a problem caused by myself.
