### ISSUE TITLE
Matlab core function `fprintf` support

### ISSUE THREAD

**Issue by APgEDo** [mat2py/mat2py#53]
## 🚀 Feature Request

Function `fprintf` is not implemented, yet.

## 🔈 Motivation

For command line and file outputs in Matlab  `fprintf` function is used. It would be great to have this function integrated to generate (file) output inside the mat2py converted python functions.

## 📝 Expected Results

```python
    def test_fprintf_function(self):
        A = M[[1.1, 123456]]
        B = M[
            [0.3, -5.7],
            [1.2, 9823],
            [0, 42],
        ]
        a = M[[1.02, 3.04, 5.06]]
        x = M[0:0.1:1]
        _M = M[
            x,
            exp(x),
        ]
        result1 = "Value A is 1.10 and value B is 123456.000\nValue A is 0.30 and value B is    1.200\nValue A is 0.00 and value B is   -5.700"
        result2 = "Value A is 9823.00 and value B is   42.000"
        result3 = M[
            ["x", "exp(x)"],
            [0.00, 1.00000000],
            [0.10, 1.10517092],
            [0.20, 1.22140276],
            [0.30, 1.34985881],
            [0.40, 1.49182470],
            [0.50, 1.64872127],
            [0.60, 1.82211880],
            [0.70, 2.01375271],
            [0.80, 2.22554093],
            [0.90, 2.45960311],
            [1.00, 2.71828183],
        ]
        formatSpec = "Value A is %4.2f and value B is %8.3f\n"

        # I do not know what would be a proper way to assert the command line output
        # capturedOutput = io.StringIO() # for pre Python3: StringIO.StringIO()
        # sys.stdout = capturedOutput
        fprintf(formatSpec, A, B)
        # assert (capturedOutput.getvalue() == result1, "Failed to print literal text and array values");
        # sys.stdout = sys.__stdout__

        # sys.stdout = capturedOutput
        fprintf("%d\n", round(a))
        # assert (capturedOutput.getvalue() == result2, "Failed to print double/float values as integers");
        # sys.stdout = sys.__stdout__

        fileID = fopen("test.txt", "w")
        # sys.stdout = capturedOutput
        fprintf(fileID, "%6s %12s\n", "x", "exp(x)")
        fprintf(fileID, "%6.2f %12.8f\n", _M)
        # assert (capturedOutput.getvalue() == result2, "Failed to print double/float values as integers");
        fclose(fileID)
        # sys.stdout = sys.__stdout__
```

**Comment by chaoqing** [comment]
Hi @APgEDo, could you provide the original Matlab code? I prefer the raw Matlab code in all those feature requests because I may adapt the code or update the `mh_python` later.

BTW, right now the I/O functions in Matlab may not be my first priority for now. I think Python is better at those I/O aspects so I want to more focus on the computation side. Hence I may implement only frequent used parts for those Matlab functions.

**Comment by APgEDo** [comment]
```matlab
A = [1.1, 123456];
B = [0.3, -5.7 ; 
      1.2, 9823;
        0, 42];
a = [1.02, 3.04, 5.06];
x = 0:.1:1;
M = [x; exp(x)];
result1 = "Value A is 1.10 and value B is 123456.000\nValue A is 0.30 and value B is    1.200\nValue A is 0.00 and value B is   -5.700"
result2 = "Value A is 9823.00 and value B is   42.000"
result3 = ["x",  "exp(x)";
    0.00,  1.00000000;
    0.10,  1.10517092;
    0.20,  1.22140276;
    0.30,  1.34985881;
    0.40,  1.49182470;
    0.50,  1.64872127;
    0.60,  1.82211880;
    0.70,  2.01375271;
    0.80,  2.22554093;
    0.90,  2.45960311;
    1.00,  2.71828183];

formatSpec = 'Value A is %4.2f and value B is %8.3f\n';
fprintf(formatSpec,A,B)
%assert(output == result1,"Failed to print literal text and array values");

fprintf('%d\n',round(a));
%assert(output == result2,"Failed to print double/float values as integers");

fileID = fopen('test.txt','w');
fprintf(fileID,'%6s %12s\n','x','exp(x)');
fprintf(fileID,'%6.2f %12.8f\n',M);
fclose(fileID);
%assert(fileoutput == result3,"Failed to write tabular data to file");
```

**Comment by APgEDo** [comment]
> BTW, right now the I/O functions in Matlab may not be my first priority for now. I think Python is better at those I/O aspects so I want to more focus on the computation side. Hence I may implement only frequent used parts for those Matlab functions.

Yes, I totally understand this. I am just asking for `fprintf` as this is called a lot inside the computational functions to "debug" or "check" if things are working as expected.

**Comment by chaoqing** [comment]
I am implementing this. But before I finish, you can insert following code **after** `from mat2py.core import *` to bypass those logging purpose functions.

```python
def fprintf(*_, **__):
    pass
fopen = fclose = fprintf
```

**Comment by chaoqing** [comment]
It is done. Check [here](https://github.com/mat2py/mat2py/blob/main/tests/test_iofun.py).

**Comment by APgEDo** [comment]
Works like a charm - thanks!

**Comment by APgEDo** [comment]
Dear @chaoqing, as I open a logging file with Pythons function `open` and get a `TextIOWrapper` class object, which I pass to my mat2py Python function, I get an issue for `fprintf(TextIOWrapper, Text)` as `isinstance(fileID, FileIdentifier)` call inside `fprintf` function will not work in the expected manor.
This is a result of me not using the Matlab `fopen` function, but Python's built-in open function in my import/export function. But at some point both worlds (mat2py Python code vs. Python code) will have to interact. The funny thing is that for the time where `fprintf` was not implemented I used `disp` function and with that it worked like a charm. Is it possible to add `IOBase` class to your `isinstance` call in order to take care for `TextIOWrapper` and other `IOWrapper` instances?

**Comment by chaoqing** [comment]
Please refer to the unit test [here](https://github.com/mat2py/mat2py/blob/e769821e37c3f1b5f64f082912c72effa657dba9/tests/test_iofun.py#L20) on how to interact with Python based io.

**Comment by APgEDo** [comment]
Thanks, after I converted the TextIOWrapper to a FileID via `fileid = openedFiles.insert(fileobj, start_id=3)  # Notice: must start from 3 as 0,1,2 reserved for std` everything works without problems.
