### ISSUE TITLE
Errors using M function and pandas.read_csv function

### ISSUE THREAD

**Issue by APgEDo** [mat2py/mat2py#54]
## 🐛 Bug Report

The bug is causing errors when using mat2py `M `function in combination with other python libraries (pandas).

## 🔬 How To Reproduce
The bug is only reproducible when compiling in debug mode. 
I tried a lot to reproduce the errors with a minimal reproducible example (see below), as the error does not show up for my unit test as well.  Therefore I started successively deleting more and more code not triggering the error and ended up with two relevant "components" needed to reproduce the bug:
`pandas.read_csv` function and `mat2py.M` function. To be more precise this ONLY worked for me when using the `read_csv` argument `header`. Opposite to my initial assumption, that the behaviour was related to `floor` function or to `for` loops, the behaviour seems solely connected to the mat2py `M` function.

As both functions are not directly interacting or passing variables, but both are using numpy, I assume that there is a declaration or class named identically causing the mess, but I do not know and do not understand processes good enough to analyse this.

### Code sample

```python
import pandas as pd
from mat2py.core import M, disp

if __name__ == '__main__':
    idat = open("test_data.txt")
    disp(idat)
    dat = pd.read_csv(idat, header=None)
    disp(dat[0])
    idat.close()

    mtarray = M[1: 6.0]
```

### `Environment`
* OS: Windows 10
* Python version: 3.10.2
* Numpy version: 1.22.3
* mat2py version: 0.0.16
* Pandas verson: 1.4.1

## 📈 Expected behavior

There should be no errors running this example, but this output:
```bash
<_io.TextIOWrapper name='test_data.txt' mode='r' encoding='cp1252'>
0    0.0100
1    0.0126
2    0.0158
Name: 0, dtype: float64
```

## 📎 Additional context

I attached my input file test_data.txt.
[test_data.txt](https://github.com/mat2py/mat2py/files/8686171/test_data.txt)

**Comment by chaoqing** [comment]
I am confused. The output is correct when you call `disp`.

```
import pandas as pd
from mat2py.core import M, disp

if __name__ == '__main__':
    idat = open("test_data.txt")
    disp(idat)
#<_io.TextIOWrapper name='test_data.txt' mode='r' encoding='cp1252'>
    dat = pd.read_csv(idat, header=None)
    disp(dat[0])
#0    0.0100
#1    0.0126
#2    0.0158
#Name: 0, dtype: float64

    idat.close()

    mtarray = M[1: 6.0]
```

**Comment by APgEDo** [comment]
Well, yes - in standard compilation mode this works for me aswell, but in **debug** mode this example does not work anymore.

**Comment by chaoqing** [comment]
I will put this issue aside for now as I can not reproduce it even in debug mode.

**Comment by APgEDo** [comment]
As it seems that this bug is not clearly reproducible, I will close this bug report.
