### ISSUE TITLE
name 'square' is not defined

### ISSUE THREAD

**Issue by leomiquelutti** [mat2py/mat2py#55]
## 🐛 Bug Report

I used `mat2py` to convert the code presented in [here](https://www.physicsforums.com/threads/reconstruct-a-signal-by-determining-the-n-fourier-coefficients.982179/).

When I try to run the converted code in Python, I get

```
Exception has occurred: NameError
name 'square' is not defined
```

## 🔬 How To Reproduce

1. The matlab script can be found in [this website](https://www.physicsforums.com/threads/reconstruct-a-signal-by-determining-the-n-fourier-coefficients.982179) or [this converted file](https://drive.google.com/file/d/1-iDLVMaoNlWoBwRGuC-dGtxor5qeutA5/view?usp=sharing).
2. Upload the `.m` file to [this Google Colab](https://colab.research.google.com/drive/10sU2NC7AktvdjmBkk5mhqObzndzL5hsX?usp=sharing) to convert it. 
3. After you convert it, copy the function in `matlab.py` to some cell, adapt it (as done in the Colab), and try to run. 

### Code sample

The conversion is similar to this:

```
import mat2py as mp
from mat2py.core import *

T = 40
t = M[0:.1:T]
dt = (23 / 40) * 100
X1 = square(mrdivide((t * 2) @ M[pi], T), dt)
subplot(3, 1, 1)
plot(t, X1)
N = length(t)
k = M[0:(N - 1)]
A = zeros(1, N)
for n in M[0:(N - 1)]:
    A[I[n + 1]] = (M[mrdivide(1, N)]) @ sum(X1 * exp(mrdivide(((((-1j) * 2) * pi) @ M[n]) @ M[k], N)))

f = mrdivide((M[0:(N - 1)]) * 1, T)
subplot(3, 1, 2)
absA = abs(A)
bar(f(M[1:int32(N / 2)]), absA(M[1:int32(N / 2)]))
xlabel('Frequency')
ylabel('Amplitude')
X2 = zeros(1, N)
n = M[0:(N - 1)]
for i in M[1:N]:
    k = i - 1
    X2[I[i]] = sum(real(A * exp(mrdivide((((1j * 2) * pi) @ M[n]) @ M[k], N))))

subplot(3, 1, 3)
plot(t, X2)
```

### Environment

Google Colab.
* OS: Linux 
* Python: 3.7.13 (default, Apr 24 2022, 01:04:09) 
* [GCC 7.5.0]
* Numpy: 1.21.6
* Scipy: 1.7.3
* Mat2Py: unknown

## 📈 Expected behavior

Run the converted function in Python without errors, and get the same outputs as in [here](https://www.physicsforums.com/threads/reconstruct-a-signal-by-determining-the-n-fourier-coefficients.982179/).

**Comment by chaoqing** [comment]
Hi @leomiquelutti, the issue is because `square` comes from signal toolbox but currently only Matlab core toolbox is implemented. Anyway, give me some time to make the example you mentioned work.

**Comment by chaoqing** [comment]
Hi @leomiquelutti, I did a quick experiment on the example you showed and got exactly the same result. You can find the example [here](https://github.com/mat2py/mat2py/blob/f9c7ddc79369dc6b39fbf5271d0b7cd946338ea1/examples/gallery/ReconstructSignal.py#L58). To solve the `square` problem, I copied the code from Matlab directly (removed some unimportant parts). And the original Matlab example code also need a few tweaks to bypass Mat2py restriction. You can compare the modified version with original one if interested.
