### ISSUE TITLE
Matlab core function `atan` support

### ISSUE THREAD

**Issue by APgEDo** [mat2py/mat2py#56]
## 🚀 Feature Request

Function `atan` is not implemented, yet.

## 🔈 Motivation

It would be great to have an implementation of  `atan` function.

## 📝 Expected Results

```matlab
x1 = sqrt(3);
x2 = [0.5i 1+3i -2.2+i];
y1corr = pi;
y2corr = [0.000000000000000 + 0.549306144334055i  1.461461853857926 + 0.305943857905529i -1.201888796734664 + 0.150593038980253i];

y1 = 3*atan(x1)
assert(y1 == y1corr, "Failed for real values")

y2 = atan(x2)
assert(isequal(round(y2,10), round(y2corr,10)), "Failed for complex values with imaginary part")
```

**Comment by chaoqing** [comment]
This is already implemented, I just did not publish a new pypi version for it. You can always install mat2py from github directly to get latest version: `python3 -m pip install -U git+https://github.com/mat2py/mat2py`.

**Comment by APgEDo** [comment]
Thanks, after upgrading it works like a charm.
