### ISSUE TITLE
Your example demo_fft is not working

### ISSUE THREAD

**Issue by RobBW** [mat2py/mat2py#58]
## 🐛 Bug Report

A fresh installation of mat2py and misshit does not pass the demo_fft test

## 🔬 How To Reproduce

run demo_fft after an up to date installation

1. ...

### Code sample

`python3 demo_fft.py
Traceback (most recent call last):
  File "/Users/robbw/demo_fft.py", line 37, in <module>
    demo_fft()
  File "/Users/robbw/demo_fft.py", line 32, in demo_fft
    y = sinc(Ts - T) @ M[x]
NameError: name 'sinc' is not defined`

### Environment

* OS:macOS Ventura
* Python version, get it with: Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ] on darwin

##
 the problem is solved caused buy a funnier to call in the toolbox.
 I fixed the problem and got the expected result by adding the following line to my demo_fft code:
`from mat2py.toolbox.signal.signal import *`

**Comment by RobBW** [comment]
My final paragraph got mangled by dictation. The corrected words are:
The problem is caused by failure to call in the toolbox folder.
I fixed the problem and got the expected result by adding the following line to my **demo_fft** code:
from `mat2py.toolbox.signal.signal import *`

**Comment by chaoqing** [comment]
Thanks for reporting. I have updated the README to the correct script path.

Yes your way to import `sinc` is correct. By default `mh_python` converted script will only import Matlab core functions and `sinc` is not one of them. Beside import it from `signal` package, another way is just copy/paste the implementation from Matlab (with `edit sinc`) into `demo_fft.m`.
