### ISSUE TITLE
Crashes with Python 3.11

### ISSUE THREAD

**Issue by thomas-haslwanter** [mat2py/mat2py#59]
## 🐛 Bug Report

Installing on a Python 3.11.x system

## 🔬 How To Reproduce

1. pip install mat2py

### Environment

* OS:  Win 11
* Python version: 3.11.4

```bash
python -c "import sys,scipy,numpy,mat2py; print(f'Python: {sys.version}\nNumpy: {numpy.__version__}\nScipy: {scipy.__version__}\nMat2Py: {mat2py.version}')"
```

### Screenshots

➜ pip install mat2py
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.7,<3.11; 0.0.10 Requires-Python >=3.7,<3.11; 0.0.11 Requires-Python >=3.7,<3.11; 0.0.12 Requires-Python >=3.7,<3.11; 0.0.13 Requires-Python >=3.7,<3.11; 0.0.14 Requires-Python >=3.7,<3.11; 0.0.15 Requires-Python >=3.7,<3.11; 0.0.16 Requires-Python >=3.7,<3.11; 0.0.17 Requires-Python >=3.7,<3.11; 0.0.18 Requires-Python >=3.7,<3.11; 0.0.19 Requires-Python >=3.7,<3.11; 0.0.2 Requires-Python >=3.7,<3.11; 0.0.20 Requires-Python >=3.7,<3.11; 0.0.21 Requires-Python >=3.7,<3.11; 0.0.3 Requires-Python >=3.7,<3.11; 0.0.4 Requires-Python >=3.7,<3.11; 0.0.6 Requires-Python >=3.7,<3.11; 0.0.7 Requires-Python >=3.7,<3.11; 0.0.8 Requires-Python >=3.7,<3.11; 0.0.9 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement mat2py (from versions: none)
ERROR: No matching distribution found for mat2py

**Comment by chaoqing** [comment]
Dependency updated to support python3.11, try `pip install -U mat2py` again.
